spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:./h2db/sampledb
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false
server:
  port: 8080

